version: 2
updates:
  # Configuração para pacotes NPM / Yarn
  - package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly" # Pode ser daily, weekly ou monthly

  target-branch: "development"